# Generated by Django 2.2.3 on 2019-07-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('link', models.URLField()),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
