# Generated by Django 2.2.3 on 2019-07-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_scraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='company_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='og_description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='og_image',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='og_title',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='og_url',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='raw_title',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='raw_url',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='s3_object_id',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='data_id',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
