# Generated by Django 2.2.3 on 2019-07-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_scraper', '0003_auto_20190716_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='company_name',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='data_id',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='s3_object_id',
            field=models.TextField(default=None),
        ),
    ]
