# Generated by Django 2.2.3 on 2019-07-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_scraper', '0004_auto_20190716_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='company_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
