# Generated by Django 2.2.3 on 2019-07-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_scraper', '0005_auto_20190717_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='company_name',
            field=models.TextField(default=None),
        ),
    ]
