# Generated by Django 2.2.3 on 2019-07-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_scraper', '0006_auto_20190717_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='raw_url',
            field=models.TextField(default=None),
        ),
    ]
