# Generated by Django 2.2.3 on 2019-07-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_scraper', '0007_auto_20190717_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='og_description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='og_image',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='og_title',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='og_url',
            field=models.TextField(default=None),
        ),
    ]
