# Generated by Django 2.2.3 on 2019-07-17 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed_scraper', '0008_auto_20190717_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='og_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='og_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='og_url',
        ),
    ]
