# Generated by Django 2.2.3 on 2019-07-29 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed_scraper', '0009_auto_20190717_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='raw_url',
        ),
    ]
